%!Rnw root = ../../Master.Rnw

\section{STAT 1600 Statistics and Data Analysis Slides}

\begin{frame}[fragile]{Statistics and Data Analysis}

Lecture 2 Knowledge and data

\end{frame}

\begin{frame}[fragile]{Outline}

Data Presentation \# 1

\begin{itemize}
\item Statistics and Data
\item Variable Types
\item Summarizing Categorical Data
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Knowledge and data}

\begin{itemize}
\item Step-by-step knowledge building
\item Some fallacies in interpreting evidence
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step by step}

1. Conceptualize the problem

\begin{itemize}
\item This is the problem of interest.  State it broadly.
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step by step}

2. Operationalize the problem

\begin{itemize}
\item The investigator formulates specific questions to answer
\item What do you want to measure?  These will become your dependent variables.
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step by step}

3. Design the Study

\begin{itemize}
\item How will you select your sample?
\item How many groups will you compare?
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step by step}

4. Collect the Data

\begin{itemize}
\item What instrument or technique will you use to collect data?
\item Will you use a survey, questionnaire, interview, observation?
\item Are you measuring a variable that will require special equipment/technology?
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step by step}

5. Analyze the Data

\begin{itemize}
\item Are you comparing means? Percentages?
\item Are differences statistically significant?
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step by step}

6. Conclusions

\begin{itemize}
\item Do the results generalize to a larger population?
\item Did you show cause-and-effect or just associations?
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step-by-step}

7. Disseminate results

\begin{itemize}
\item How are you sharing your results?  
\item News reports? 
\item Scientific journals? 
\item Etc…
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Step-by-step Knowledge Building }

\begin{itemize}
\item Conceptualize the problem -- broad wording
\item Operationalize the problem -- specific questions
\item Design the Study -- how to select samples
\item Collect the Data -- measurement instrument
\item Analyze the Data -- comparing what
\item Conclusions -- repeatability and generalization
\item Disseminate results -- presenation of results
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Example -- comparing wt loss program}

\begin{itemize}
\item Zone
  \begin{itemize}
  \item Balances carbohydrates, protein, fat
  \end{itemize}
\item Atkins
  \begin{itemize}
  \item Low carbohydrate, high fat, unrestricted calories
  \end{itemize}
\item LEARN
  \begin{itemize}
  \item Low fat, and based on national guidelines
  \end{itemize}
\item Ornish
  \begin{itemize}
  \item Low fat, high carbohydrate, unrestricted calories
  \end{itemize}
\end{itemize}

How are we going to design a study to compare these?
\end{frame}

\begin{frame}[fragile]{Building knowledge step-by-step}

1. Conceptualize the problem

\begin{itemize}
\item Which weight loss program is most effective?
\item Which one is most healthy?
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step-by-step}

2. Operationalize the problem

\begin{itemize}
\item How do we measure `effective' and `healthy?'
\item At what time point are we interested in measuring? In 2 weeks, 2 months, 2 years?
\item Are we comparing average weight loss or perhaps the percentage of people who lost 15 pounds or more?
\item How do we measure healthy?  LDL cholesterol reduction, BP reduction, Glucose levels?
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step-by-step}

3. Design the Study

\begin{itemize}
\item Where are we recruiting our subjects?
\item How long will the study last?
\item Do they choose the diet or do we randomly assign them to it?
\item How do we ensure they stay on the diet?
\item What do we do with participants who go off the diet, do we eliminate them from the study?
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step-by-step}

4. Collect the Data

\begin{itemize}
\item How many times will we measure their weights?
\item Are we taking blood samples? Urine samples? Are we sending samples to lab?
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step-by-step}

5. Analyze the Data

\begin{itemize}
\item Are there significant differences in average weight loss between the diet groups?
\item Are there differences in cholesterol, blood pressure, glucose levels or other biochemistry measures relating to health?
\item Are there differences in how well participants adhere to each diet plan?
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step-by-step}

6. Conclusions

\begin{itemize}
\item After analyzing the results what do we conclude is the best diet? Why?
\item Can we generalize results to the larger population?
\item Are we sure weight loss can be attributed to the diet?
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Building knowledge step-by-step}

7. Disseminate results

\begin{itemize}
\item How are we going to present the results?
\item What tables and graphs would make the study easy to read and understand?
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Questioning results of a study}

{\small{
If we are reading the results of a study we need to be able to ask ourselves some questions:

\begin{itemize}
\item What is the long term result (perhaps the results will differ if measurements are taken at longer time points)?
\item What was the sample and to what population are we trying to generalize the results (males, females, age, ethnic differences)?  We want to make sure we can generalize to the population outside of the study sample.
\item Was the sample size large enough to allow for generalizing to the outside population?
\end{itemize}
}}
\end{frame}

\begin{frame}[fragile]{Questioning results of a study}

There is variation in study design and some studies are designed better than others.  We need to be able to judge the validity and reliability of a study.
\end{frame}

\begin{frame}[fragile]{Fallacies in interpreting evidence}

\begin{enumerate}
\item Lack of evidence
  \begin{itemize}
  \item ``No proof that the drug is unsafe''
  \item This is flawed as a lack of evidence does not mean the contrary is true and that the drug is safe
  \end{itemize}
\item Anecdotal evidence
  \begin{itemize}
  \item ``Testimonies of real people this worked for \dots''
  \item Infomercials
  \item Existence does not mean prevalence.  Perhaps the drug or supplement worked for some people, but does that mean it is effective for the broader population?
  \end{itemize}
\end{enumerate}
\end{frame}

\begin{frame}[fragile]{Fallacies in interpreting evidence}

\begin{itemize}
\item Correlation equals causation
  \begin{itemize}
  \item ``married people are happier than single people''
  \item Did marriage cause the `happier' outcome?  Maybe happy people are the ones who tend to get married.
  \item Two things happening at the same time does not mean one causes the other
  \end{itemize}
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Examples of Wrong Reasoning Leading to Wrong Conclusions}

\begin{itemize}
\item Lack of evidence fallacy.  The fallacy lies in the reasoning that lack of evidence means the contrary it true.
\item Anecdotal evidence fallacy.  The fallacy lies in the reasoning that existence means prevalence.
\item Correlation equals causation fallacy.  The fallacy lies in the reasoning that ``two things happening together'' must mean one causes the other.
\end{itemize}
\end{frame}
